parameters:
  poolName: 'Package ES CodeHub Lab E'
  # component-governance
  sourceScanPath: '$(Build.SourcesDirectory)'
  # credscan
  suppressionsFile: ''
  # policheck
  optionsRulesDBPath: ''
  optionsFTPath: ''
  # tsa-upload
  codeBaseName: ''
  # selections
  APIScan: true # set to false when not using Windows APIs.

jobs:
- job: compliance_job
  displayName: Run compliance tasks
  pool:
    name: ${{ parameters.poolName }}
  steps:
  - download: current

  - template: template/auto-applicability.yml

  - template: template/component-governance.yml
    parameters:
      sourceScanPath: '$(Build.SourcesDirectory)'

  - template: template/credscan.yml
    parameters:
      suppressionsFile: ''

  - template: template/defender.yml

  - template: template/policheck.yml
    parameters:
      optionsRulesDBPath: ''
      optionsFTPath: ''

  - template: template/vulnerability-assessment.yml

  - template: template/publish-security-logs.yml

  - template: template/tsa-upload.yml
    parameters:
      codeBaseName: ''

  - template: template/sdtreport.yml
    parameters:
      APIScan: ${{ parameters.APIScan }}
      BinSkim: true
      CredScan: true
      PoliCheck: true
